### ISSUE TITLE
Compile

### ISSUE THREAD

**Issue by Proxcom** [IamFlea/bartender#10]
Hello, sorry to bother you, the compiled .exe files is not availble on your website, would you please release these ? I don't know how to compile your project.
Sorry again

**Comment by IamFlea** [comment]
Howdy, 

you don't need to apology. I compiled the project into executable files (exe) for an antique version of Bartender. That version was using print screens in order to find out researches.. However, I used a different approach here and I couldn't create executable files because of some libraries.

Anyway, you don't need to compile it, but you need to have Python 3.6. However, you need to download two dependencies PyQT5 and pywin32, see https://github.com/IamFlea/bartender#dependencies  There are links for that. You can also download QT and pywin via command `pip3 install PyQt5` and `pip3 install pywin32`. After you get the required libraries, then you simply run the script with `python3 bartender.py` 

However, I haven't played AoE for ages and it might need to update some offsets in order to run the program. So it might fail running.
